Repository LABHDUFBA/labhdufba.github.io, pull requests merged in 2024-03, with the labels that each got.

#1 Add workflow hugo.yaml
  .github/workflows/hugo.yaml
Labels: workflow

#5 Correção do local da imagem de perfil do membro
  assets/images/eric-brasil.png
Labels: testes

#6 infos sobre Leonardo
  assets/images/leonardo-nascimento.jpeg
  content/english/authors/leonardo-nascimento.md
Labels: testes

#7 Nova aba para "Team" e update de dados de membros
  assets/images/leonardo-nascimento.png
  config/_default/menus.en.toml
  content/english/team/_index.md
  content/english/team/eric-brasil.md
  content/english/team/leonardo-nascimento.md
Labels: testes

#8 Novos testes de configuração geral
  config/_default/languages.toml
  config/_default/menus.en.toml
  config/_default/params.toml
Labels: testes

#9 Testes com página inicial, imagens, aba pesquisa
  assets/images/join-us.webp
  assets/images/labhd.png
  assets/images/leonardo-nascimento.jpeg
  assets/images/research-data-mining.webp
  assets/images/research-digital-history.webp
  config/_default/menus.en.toml
  content/english/_index.md
  content/english/about/_index.md
  content/english/authors/_index.md
  content/english/authors/john-doe.md
  content/english/authors/sam-wilson.md
  content/english/authors/william-jacob.md
  content/english/pages/research/_index.md
  content/english/pages/research/data-mining.md
Labels: testes

#10 Update da página inicial, correção de images, add pesquisa
  assets/images/join-us.png
  assets/images/join-us.webp
  assets/images/research-data-mining.png
  assets/images/research-data-mining.webp
  assets/images/research-digital-history.png
  assets/images/research-digital-history.webp
  content/english/_index.md
  content/english/pages/research/digital-history.md
Labels: testes

#11 Update de metadados, links de redes sociais, imagens, menus
  config/_default/menus.en.toml
  config/_default/params.toml
  content/english/authors/eric-brasil.md
  content/english/pages/research/digital-history.md
  content/english/sections/testimonial.md
  content/english/team/_index.md
  content/english/team/eric-brasil.md
  content/english/team/leonardo-nascimento.md
  data/social.json
  hugo.toml
Labels: testes

#12 Correção de sintaxe do arquivo toml
  hugo.toml
Labels: testes

#14 Updates
  assets/images/bruno.png
  assets/images/leticia.png
  assets/images/rosana.png
  config/_default/menus.en.toml
  content/english/authors/bruno-duraes.md
  content/english/authors/leticia.md
  content/english/authors/rosana.md
  content/english/pages/midia.md
  content/english/pages/publications.md
  content/english/pages/tools.md
  data/theme.json
Labels: config-inicial
